; =============================================================================
; Smart Fridge — Load Cell Calibration
; Board: Dasduino ESP32-WROVER-E
; Run this LAST after all other components are confirmed working
; =============================================================================
[env:esp32wrover]
platform              = espressif32
board                 = esp32dev
framework             = arduino

board_build.arduino.memory_type = qio_opi
build_flags           =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

monitor_speed         = 115200
upload_speed          = 921600

lib_deps =
    bogde/HX711 @ ^0.7.5
