; =============================================================================
; Smart Fridge — Main Controller
; Board: Dasduino ESP32-WROVER-E
; =============================================================================
[env:esp32wrover]
platform              = espressif32
board                 = esp32dev
framework             = arduino

build_flags           = -DBOARD_HAS_PSRAM

; Serial monitor
monitor_speed         = 115200
upload_speed          = 921600

; Libraries
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    bogde/HX711 @ ^0.7.5
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
    adafruit/Adafruit GFX Library @ ^1.11.9
    https://github.com/thinger-io/Arduino-Library.git